name: "CI"

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

defaults:
  run:
    shell: bash -l {0}

jobs:
  tests:
    runs-on: ubuntu-latest
    name: "tests"
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - uses: conda-incubator/setup-miniconda@v2
        with:
            auto-update-conda: true
            use-mamba: true
            python-version: 3.9 
            miniforge-variant: Mambaforge
            environment-file: environment.yml
            activate-environment: openfe       
      - name: "Environment Information"
        run: |
          mamba info -a
          mamba list
